import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FaUserCircle, FaCalendar, FaPhone, FaMapMarkerAlt, FaLock } from 'react-icons/fa';
import api from '../services/api';

const SharedProfile = () => {
    const { token } = useParams();
    const [profile, setProfile] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        const fetchSharedProfile = async () => {
            try {
                // Determine if we are hitting the gateway locally
                const response = await api.get(`/patients/share/${token}`);
                setProfile(response.data.data);
            } catch (err) {
                setError('Invalid or expired share link.');
            } finally {
                setLoading(false);
            }
        };
        fetchSharedProfile();
    }, [token]);

    if (loading) return <div className="page-container">Loading...</div>;
    if (error) return <div className="page-container"><div className="error-msg">{error}</div></div>;

    return (
        <div className="page-container" style={{ alignItems: 'flex-start', paddingTop: '4rem' }}>
            <motion.div
                className="card"
                style={{ width: '100%', maxWidth: '600px' }}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
            >
                <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
                    <div style={{ display: 'inline-flex', padding: '0.5rem 1rem', background: '#ECFDF5', borderRadius: '999px', color: 'var(--primary-dark)', fontSize: '0.875rem', fontWeight: 500, alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                        <FaLock size={12} /> Secure Shared View
                    </div>
                    <FaUserCircle size={80} color="var(--primary)" style={{ display: 'block', margin: '0 auto 1rem' }} />
                    <h1 style={{ fontSize: '1.75rem', fontWeight: 700 }}>{profile.full_name}</h1>
                    <p style={{ color: 'var(--text-muted)' }}>Patient Medical Profile</p>
                </div>

                <div style={{ display: 'grid', gap: '1rem' }}>
                    <ShareItem icon={<FaCalendar />} label="Date of Birth" value={new Date(profile.date_of_birth).toLocaleDateString()} />
                    <ShareItem icon={<FaUserCircle />} label="Gender" value={profile.gender} />
                    <ShareItem icon={<FaPhone />} label="Phone" value={profile.phone} />
                    <ShareItem icon={<FaMapMarkerAlt />} label="Address" value={profile.address} />
                </div>

                <div style={{ marginTop: '2rem', paddingTop: '1.5rem', borderTop: '1px solid #E5E7EB', textAlign: 'center', fontSize: '0.875rem', color: 'var(--text-muted)' }}>
                    Generated by Health Bar Secure Sharing
                </div>
            </motion.div>
        </div>
    );
};

const ShareItem = ({ icon, label, value }) => (
    <div style={{ display: 'flex', alignItems: 'center', padding: '1rem', background: '#F9FAFB', borderRadius: 'var(--radius)' }}>
        <div style={{ width: '40px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--white)', borderRadius: '50%', border: '1px solid #E5E7EB', color: 'var(--primary)', marginRight: '1rem' }}>
            {icon}
        </div>
        <div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</div>
            <div style={{ fontWeight: 500 }}>{value || 'N/A'}</div>
        </div>
    </div>
);

export default SharedProfile;
